name: deploy to gitee

on:
  schedule:
    - cron: "0 0/1 * * *"
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: oprypin/find-latest-tag@v1
        id: sib-latest-tag
        with:
          repository: SonicCloudOrg/sonic-ios-bridge
          
      - uses: oprypin/find-latest-tag@v1
        id: sgm-latest-tag
        with:
          repository: SonicCloudOrg/sonic-go-mitmproxy

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'version.json'
          prefix: test

      - name: replace sib
        run: |
          sib_new_ver=${{ steps.sib-latest-tag.outputs.tag }}
          sib_new_ver_sub=${sib_new_ver:1}
          sib_old_ver=${{ env.test_sib }}
          sib_old_ver_sub=${sib_old_ver:4}
          sed -i "s/${sib_old_ver}/sib_${sib_new_ver_sub}/g" version.json
          sed -i "s/${sib_old_ver_sub}/${sib_new_ver_sub}/g" src/markdown/sib/re-sib.md
          
      - name: replace sgm
        run: |
          sgm_new_ver=${{ steps.sgm-latest-tag.outputs.tag }}
          sgm_new_ver_sub=${sgm_new_ver:1}
          sgm_old_ver=${{ env.test_sgm }}
          sgm_old_ver_sub=${sgm_old_ver:4}
          sed -i "s/${sgm_old_ver}/sgm_${sgm_new_ver_sub}/g" version.json
          sed -i "s/${sgm_old_ver_sub}/${sgm_new_ver_sub}/g" src/markdown/sgm/re-sgm.md

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update doc files.
          author: GitHub <noreply@github.com>
          signoff: false
          branch: deploy
          base: main
          labels: document
          delete-branch: false
          title: 'doc: update files and ready to deploy'
          body: |
            **在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：**
            
            - [x] 标题为fix、feat或doc开头
            - [x] 我已检查没有与此请求重复的拉取请求。
            - [x] 我已经考虑过，并确认这份呈件对其他人很有价值。
            - [x] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
            
            **填写PR内容：**
            
            - Update files to deploy by bot 🚀.
            
          draft: false
          
      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          
      - id: automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          MERGE_LABELS: "document"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ steps.cpr.outputs.pull-request-number }}
          MERGE_RETRIES: 18
          MERGE_RETRY_SLEEP: 10000
          
      - name: upload files to OSS
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: sonic-assets-hongkong
          endpoint: oss-cn-hongkong.aliyuncs.com
          folder: dist/
          incremental: false
          
      - name: sync gitee
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
         remote_repo="https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_PASSWORD }}@gitee.com/sonic-cloud/sonic-cloud.git"
         git remote add gitee "${remote_repo}"
         git show-ref # useful for debugging
         git branch --verbose
         git push --all --force gitee
         git push --tags --force gitee

      - name: Build Gitee Pages
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: sonic-cloud/sonic-cloud
          branch: deploy
          directory: dist
          https: false
