name: deploy to gitee

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update index.html file.
          author: GitHub <noreply@github.com>
          signoff: false
          branch: doc/deploy
          base: main
          labels: document
          delete-branch: true
          title: 'doc: update index.html files version to deploy'
          body: |
            **在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：**
            
            - [x] 标题为fix、feat或doc开头
            - [x] 我已检查没有与此请求重复的拉取请求。
            - [x] 我已经考虑过，并确认这份呈件对其他人很有价值。
            - [x] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
            
            **填写PR内容：**
            
            - Update index.html files to deploy by bot 🚀.
            
          draft: false
          
      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          MERGE_LABELS: "document"
          MERGE_DELETE_BRANCH: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ steps.cpr.outputs.pull-request-number }}
          MERGE_RETRIES: 18
          MERGE_RETRY_SLEEP: 10000
          
      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: sonic-assets-hongkong
          endpoint: oss-cn-hongkong.aliyuncs.com
          folder: dist/
          incremental: false
          
      - name: sync gitee
        run: |
         remote_repo="https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_PASSWORD }}@gitee.com/sonic-cloud/sonic-cloud.git"
         git remote add gitee "${remote_repo}"
         git show-ref # useful for debugging
         git branch --verbose
         git push --all --force gitee
         git push --tags --force gitee

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: sonic-cloud/sonic-cloud
          branch: main
